### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by TheLightSpirit** [Jisagi/Discord-guild-copy#20]
Hi!

I have translate your guide in french in : https://github.com/TheLightSpirit/Discord-guild-copy
I have translate that because i think the french community of Discord need this and it's a very good job !

**Comment by Jisagi** [comment]
Thank you very much for the contribution. I added your translation with a link at the top in the english readme and also added a Credits section. Since there isn't a lot of changes in the readme it can probalby stay like this without the need for fixes. If you find anything you want to fix or add upcoming readme cahnges to the french version, feel free to open a pull request.

**Comment by TheLightSpirit** [comment]
I'm proud to help you ! If you want, I can translate the guide of SeedMiner and SteelMiner. I know a Discord Server named DarkFélin about hack, in french and they not speak english, so, I can help

**Comment by Jisagi** [comment]
Thank for the offer, but Seedminer recently got added to 3ds.hacks.guide which already has a public [translation project](https://crowdin.com/project/3ds-guide). Steelminer is not really worth the time to be translated and the time needed to implement something to be able to add translations in a decent way is just too much time.
I do work on something for the guild-copy script though which will let people translate the whole output the script gives.

**Comment by TheLightSpirit** [comment]
i look, it does not matter.
Thanks you
