### ISSUE TITLE
;-;

### ISSUE THREAD

**Issue by OdarGM** [Jisagi/Discord-guild-copy#21]
TypeError: Cannot read property 'new' of undefined
    at options.overwrites.textChannel.permOverwrites.map.permOver 
\objects\creator.js:219:80

**Comment by OdarGM** [comment]
```js
if (!textChannel.permLocked) {
                        options.overwrites = textChannel.permOverwrites.map(permOver => {
                            return {
                                id: guildData.references.roles.get(permOver.id).new.id,
                                allow: new Permissions(permOver.allowed),
                                deny: new Permissions(permOver.denied),
                            };
                        });
                    }
```

**Comment by Jisagi** [comment]
I cannot reproduce it with the latest verison of the script and d.js. Try to redownload the repository and create a new backup file. The existing one might be corrupted for some reason.
If the new one still doesn't work feel free to upload the guildData.json somewhere like pastebin so i can test it myself.

**Comment by OdarGM** [comment]
kk

**Comment by Jisagi** [comment]
The problem seems to be the role with the id 417673415940505600 which has permission overrides in the text channel named 'tests'. This role does exist in the channel overrides but not as role itself (in the guildData.json) for some reason.
I can't see the name of this certain role, since its only listed in the text channel overrides, so it was either not serialized which is strange, or it was deleted inbetween the backup creation which is highly unlikely. The easy solution would be to delete the permission overrides from the guidlData.json or we try to find out what this certain role is.
I worte this small script, which outputs all roles on the original server and their ids. You just need to save the file with .js as extension into the discord-guild-copy folder and run it with 'node filename.js'. It will use the data (token, ids, etc.) from the existing settings, so nothing further for you to edit. The role we search for should be marked with 4x '!' at the beginning (hopefully). If we can find the error i can fix it, otherwise i'll fix your backupfile and send you a working one.

**Comment by OdarGM** [comment]
fixed
