### ISSUE TITLE
Discord crashing bot action too fast

### ISSUE THREAD

**Issue by bartolinek221** [Jisagi/Discord-guild-copy#25]
Hello i reccomend to add a delay before any action on channels like 1sec delay after delete any channel becouse its crashing discord on pc: i5 7500 16gb ram rx480 and need restart of disc becouse you still see removed channels just server lagged

**Comment by Jisagi** [comment]
I never saw a discord crash when testing the script even with 200+ channels to delete on a server. The fact that you still see channel is just lag and can be fixed by restarting discord which only takes a few seconds. I will not add a delay for deletion because the documentation clearly says "A **preferably empty guild** which can be overwritten". If you don't want this "lag" to surface, don't use large guilds to overwrite but an empty one.
Also, your discord client crashing doesn't stop the script from executing, so it'll still work, even without any normal user client opened in the first place.
