### ISSUE TITLE
Invalid role

### ISSUE THREAD

**Issue by snaildos** [Jisagi/Discord-guild-copy#45]
Language English selected. Translated by Jisagi
Successfully logged in as Backup2001#2501. Starting script
Latest discord.js version installed
Latest script version installed
1. Serializing general data
2. Serializing role data
3. Serializing category data
4. Serializing text channel data
5. Serializing voice channel data
6. Serializing emojis
7. Serializing bans
8. Saving guild data to file
9. Serialization finished and data successfully saved
10. Deleting channels
11. Deleting roles
Invalid Role

I am getting that error

- Node.js version: v10.15.0
- Operating system: Windows 10

**Comment by Jisagi** [comment]
I just pushed a new commit. This likely happens due to a role being a managed role and therefore not being deletable. Maybe a role autocreated for a Bot or one of the Nitro Booster roles. They will now be skipped when clearing the new guild.
To update, just redownload the latest version of the script.
