### ISSUE TITLE
doesn't seem to know my version

### ISSUE THREAD

**Issue by thewilloftheshadow** [Jisagi/Discord-guild-copy#47]
```
isagi-discord-guild-copy-10:~ 15:23 
$ node copy.js clone
nodejs: v10.15.3
Language English selected. Translated by Jisagi
Successfully logged in as Event Manager#5309. Starting script
Please update your Nodejs version to 10.0.0 or higher
```

My node version is as high as i can update it, which is higher than 10.0.0

**Comment by thewilloftheshadow** [comment]
```
app@jisagi-discord-guild-copy-10:~ 15:24 
$ node --version
v10.15.3

app@jisagi-discord-guild-copy-10:~ 15:25 
$ npm --version
6.4.1
```

**Comment by Jisagi** [comment]
As soon as the script cannot find a `package-lock.json` (or `yarn.lock`) it will throw this error. Your npm version is more than up-to-date already, since it has to be >5.1. The nodejs version itself shouldn't be the problem here.
Check if there is, in your case, a `package-lock.json` in the main folder of the script. If not, rerun `npm install`, so npm will create a new file for you.

**Comment by thewilloftheshadow** [comment]
Ahh gotcha. Yeah I don't usually have package-lock.json in my files

**Comment by Jisagi** [comment]
Since there haven't been any further problems, I will close the issue. If you still encounter any weird behaviour, just reopen the issue (or create a new one).
