### ISSUE TITLE
Cannot read "has" of undefined

### ISSUE THREAD

**Issue by MrSchwepppes** [Jisagi/Discord-guild-copy#72]
C:\Discord-guild-copy-master>node copy.js clone
nodejs: v12.8.0
Language English selected. Translated by Jisagi
Successfully logged in as <bot-name>. Starting script
Latest script version installed
Cannot read property 'has' of undefined

C:\Discord-guild-copy-master>

I've looked through the whole thing and nothing seems to be the problem, not sure where to go from here. 

**Additional information:**

- Node.js version: 13.9.0
- Operating system: Windows 10 64bit

**Comment by Jisagi** [comment]
Might be an outdated version of discord.js. Did you only run `npm install` and nothing else? The start fresh, just delete the file `package-lock.json` and the `node_modules` folder and rerun `npm install`. If it still persists, feel to enable the debug mode in the settings and post the full error if it still doesn't work after the "reinstallation" with npm

Also, even if it doesn't matter, you actual nodejs version is a bit older than the one you specified. Shouldn't be the problem here though
