### ISSUE TITLE
Problems : "client.guilds.get is not a function"

### ISSUE THREAD

**Issue by AizenAPI** [Jisagi/Discord-guild-copy#75]
**Please describe the problem you are having in detail:**

Please describe the problem in as much detail as possible. Please include any thrown error codes as well.

I use my token from my personal account (I know the risks) I do node copy.js it answers "TOKEN IVALID" Ok but when I put the token of a bot right after as you said it says "Successfully logged in as TESTT CLONER # 8996. Starting script.
client.guilds.get is not a function "

![image](https://user-images.githubusercontent.com/63105413/78361296-76747f80-75b8-11ea-945a-7509f2faebfc.png)

**Additional information:**

- Node.js version:
![image](https://user-images.githubusercontent.com/63105413/78360992-f0583900-75b7-11ea-997e-0690cb187e1d.png)

- Operating system: Windows 10

**Comment by Jisagi** [comment]
1. The "personal" token problem: It's not about the risk (anymore), but the fact, that the d.js library will not work with a non bot token at all. I obviously cannot give support for that, because I am not the one maintaining it.
2. "client.guilds.get": Seems like you are using an outdated version of the script. Redownload the newest one and try again (with the bot token).

**Comment by AizenAPI** [comment]
So there is no way to use it in selfbot

**Comment by Jisagi** [comment]
No, there is not, but that is not because of me or my script ¯\_(ツ)_/¯

**Comment by AizenAPI** [comment]
thanks anyway ¯_(ツ)_/¯
I'll try to make one using your script because "a lot" of people did it in selfbot

**Comment by Jisagi** [comment]
Since my script uses d.js, good luck changing that to run with a selfbot
