### ISSUE TITLE
Settings Issue

### ISSUE THREAD

**Issue by hithereimxplicit** [Jisagi/Discord-guild-copy#83]
Hi, I'm looking to disable this part. 
![Capture](https://user-images.githubusercontent.com/73083704/97948091-778faa00-1d5d-11eb-870d-ffe49a68853e.PNG)

**Comment by Jisagi** [comment]
You cannot disable this part in the settings because otherwise the script will not be able to clear the target guilds roles.
The only way is to manually remove the line in the code [HERE](https://github.com/Jisagi/Discord-guild-copy/blob/master/objects/validator.js#L61). I'm not sure why you would need this, but here you go.
